pre-commit:
  parallel: true
  jobs:
    - name: pint
      glob: "*.php"
      run: vendor/bin/sail composer pint -- {staged_files}
      stage_fixed: true

    - name: stan
      glob:
        - "{app,config,database,routes,tests}/*.php"
        - "bootstrap/app.php"
      exclude:
        - "database/migrations/*"
      run: vendor/bin/sail composer stan -- {staged_files}

    - name: tests
      glob: "*.php"
      run: vendor/bin/sail composer test:coverage

    - name: prettier
      glob: "*.{js,ts,jsx,tsx,vue,css,json,md,yml,yaml}"
      run: vendor/bin/sail npx prettier --write {staged_files}
      stage_fixed: true

    - name: eslint
      glob: "*.{js,ts,jsx,tsx,vue}"
      run: vendor/bin/sail npx eslint --fix {staged_files}
      stage_fixed: true

pre-push:
  parallel: true
  jobs:
    - name: rector-tests
      run: vendor/bin/sail composer rector:test:dry

    - name: mutate
      run: vendor/bin/sail composer test:mutate
