name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22,23 * * 0'
    - cron: '0 0-6 * * 1'

permissions:
  contents: read

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: run renovate
        uses: renovatebot/github-action@v46.3.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: 'false'
          LOG_LEVEL: info
