name: security

on:
  pull_request:
    branches: [staging]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: vulnerability scan
        uses: paolobellini/bellini.one/actions/general/security@v1.0
